image: Visual Studio 2019
clone_folder: C:\TBuild\tdesktop
test: off
deploy: off
configuration: Debug
skip_tags: true

environment:
  GYP_MSVS_OVERRIDE_PATH: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\'
  GYP_MSVS_VERSION: 2019
  matrix:
   - BUILD_VERSION:

matrix:
  fast_finish: true

before_build:
  - .\.appveyor\install.bat

build:
  project: Telegram\Telegram.sln
