name: Upload full source to release.

on:
  release:
    types: released

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone.
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install prerequisites.
      run: |
        pip install git-archive-all

        p=$(echo frk-v${GITHUB_REF##*/v}-full.tar.gz)
        echo "TAG=$p" >> $GITHUB_ENV
    - name: Build assets.
      run: |
        mkdir -p dist/
        echo "$TAG"
        ~/.local/bin/git-archive-all ./dist/${TAG}
    - name: Upload.
      uses: lovasoa/upload-release-asset@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./dist/${{ env.TAG }}
        asset_label: Source code (tar.gz, full)
        asset_name: ${{ env.TAG }}
        asset_content_type: application/x-gzip
